### ISSUE TITLE
Admin panel path hint not working

### ISSUE THREAD

**Issue by kandhagurug** [MagePsycho/magento2-easy-template-path-hints#2]
Admin panel path hint not working

**Comment by MagePsycho** [comment]
This has been fixed in new version.

**Comment by kandhagurug** [comment]
Thank you

On Fri, Apr 22, 2016 at 10:53 PM, Raj K Bhtt notifications@github.com
wrote:

> This has been fixed in new version.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MagePsycho/magento2-easy-template-path-hints/issues/2#issuecomment-213519410

## 

Confidentiality Notice: The above information contained in this email is 
intended for the confidential use of the above-named recipient(s). If a 
reader of this message is not the intended recipient or person responsible 
for delivering it to the intended recipient, you are hereby notified that 
you have received this communication in error, and that any review, 
dissemination, distribution, or copying of this communication is strictly 
prohibited. If you have received this in error, please notify the sender 
immediately and destroy this message.**
