### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by gosteev** [MagePsycho/magento2-easy-template-path-hints#3]
when i require composer package:

![image](https://cloud.githubusercontent.com/assets/6203574/16896472/c8756b72-4b9c-11e6-8f0b-833e0d16e2a1.png)

Magento ver. 2.1.0

**Comment by MagePsycho** [comment]
First, you have to add repository to composer configuration:

`composer config repositories.magepsychotemplatehints vcs git@github.com:MagePsycho/magento2-easy-template-path-hints`

**Comment by gosteev** [comment]
did that though

**Comment by jimzant** [comment]
Experienced the same problem described above. 
Also added:  composer config repositories.magepsychotemplatehints vcs git@github.com:MagePsycho/magento2-easy-template-path-hints

**Comment by Hexmage** [comment]
Looks like the module doesn't support magento/framework 100.1.1 which the latest magento version requires.

**Comment by gosteev** [comment]
![image](https://cloud.githubusercontent.com/assets/6203574/18518745/f4ca890a-7aa9-11e6-8ddb-52ec132dbac1.png)

**Comment by dunarri** [comment]
Workaround: install from source.

From root directory of Magento install:
mkdir -p app/code/MagePsycho
cd app/code/MagePsycho
wget "https://github.com/MagePsycho/magento2-easy-template-path-hints/archive/master.zip"
unzip master.zip
mv magento2-easy-template-path-hints-master/src Easypathhints
rm -rf magento2-easy-template-path-hints-master master.zip
cd -
bin/magento module:enable --clear-static-content MagePsycho_Easypathhints
bin/magento setup:upgrade
bin/magento setup:di:compile

**Comment by MagePsycho** [comment]
Updated the ReadMe docs for all possible types of installation.
Please check them.
