### ISSUE TITLE
magento2-easy-template-path-hints not working in Magento 2.1.3

### ISSUE THREAD

**Issue by earlelnar** [MagePsycho/magento2-easy-template-path-hints#4]
Hi,

I noticed something after installing easy path hints in my  fresh package of magento 2.1.3 in my local. 
after running all the required commands. I tried to use the easy path hints on one of the page of the site. but nothing happened. Any Ideas how to fix this? 

![easypathints](https://cloud.githubusercontent.com/assets/14094984/22057758/0fbc2cf0-dda1-11e6-9b5b-6c7f8f2d6b3d.jpg)

Thanks,

**Comment by rafalcao** [comment]
I have the same problem...

:(

**Comment by MagePsycho** [comment]
@rafalcao @mazestricks will check and get back to you guys.

**Comment by earlelnar** [comment]
Hi @MagePsycho  Thanks :)

**Comment by rafalcao** [comment]
@MagePsycho Thanks for the answer.

**Comment by stoque** [comment]
@MagePsycho  Hi bro, I'm having the same problem, i'm waiting for a solution, thx!

**Comment by josephfelix** [comment]
@MagePsycho Same problem here, can you give me a status to fix it?

**Comment by earlelnar** [comment]
@MagePsycho  How were things going with this issue in your extension? Does this work now with Magento 2.1.3?

Thanks

**Comment by stephansteiner** [comment]
Confirming that 2.1.3 and 2.1.4 are not working anymore. Apparently something has changed in Magento so that your extension stopped working.

**Comment by earlelnar** [comment]
> Yes something has changed in magento 2 that's why it's not working. I hope MagePsycho will get their attention fixing their extension.

**Comment by earlelnar** [comment]
Hi @MagePsycho 

Any updates? We've been waiting for this issue to be fix. I hope you have a great day. 

Thanks,

**Comment by tonyfelice** [comment]
<--- is willing to contribute beer money!  


(and I can confirm 2.1.6 is incompatible as well)

**Comment by earlelnar** [comment]
Hi @MagePsycho 

How is it going? Is there any progress it's been a month. But I don't see the fix.
I hope you can have time for this.

Thanks,

**Comment by MagePsycho** [comment]
Hi, Guys!

I have taken this as my next task. Hopefully will be fixed soon.

Thanks a lot for your patience.

**Comment by earlelnar** [comment]
Hello,

I hope you could fix this soon. because we've waiting for this to get fixed.

Thanks

**Comment by Sohail-Ansari** [comment]
Okay here is the SOLUTION.
Tested in Magento 2.1.6

Click Stores > Configuration > ADVANCED > Developer.

In the Scope dropdown in the upper-left corner select the view for which you want the template hints [very important.].

In the Developer Client Restrictions set your Public IP Address. [This is must else it will not work.
To find out your public IP google "what is my ip", and the first result is your IP. ***Only IP v4 [111.111.111.111] will work, It didn't support IP v6 [2001:0db8:85a3:0000:0000:8a2e:0370:7334]. ***
]

In the Debug tab, set Template Path Hints for storefront to Yes. To enable path hints for Admin set Template Path Hints for Admin to Yes.

To save the changes, click Save Config in the upper-right corner.

Clear Cache and you are done.

All the best people.

**Comment by MagePsycho** [comment]
@Sohail-Ansari Yeah,  we know the default feature of Magento. But this extension will enable the template path hints on the fly so that you don't have to go over such tedious default process.

**Comment by MagePsycho** [comment]
Cheers @mazestricks @tonyfelice @rafalcao @josephfelix @stephansteiner @Sohail-Ansari
The issue has been fixed. Please update to the latest version.
