### ISSUE TITLE
Not working on 2.1.7 via composer

### ISSUE THREAD

**Issue by aodreman-logoscorp** [MagePsycho/magento2-easy-template-path-hints#5]
Hi @MagePsycho 

After installing this via composer, I got the following error:
**PHP Fatal error:  require(): Failed opening required '/Users/aodreman/Developer/Websites/learnmagento2.dev/vendor/composer/../magepsycho/magento2-easy-template-path-hints/registration.php'**

**Comment by ryanengland** [comment]
Have submitted a pull request to fix this - hopefully @MagePsycho will merge

**Comment by MagePsycho** [comment]
@ryanengland Thanks man. Will check and merge the PR.
