### ISSUE TITLE
Cannot install via composer in Magento 2.2

### ISSUE THREAD

**Issue by boehsermoe** [MagePsycho/magento2-easy-template-path-hints#7]
After running `composer require magepsycho/magento2-easy-template-path-hints:dev-master`
Ive got this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magepsycho/magento2-easy-template-path-hints dev-master -> satisfiable by magepsycho/magento2-easy-template-path-hints[dev-master].
    - Conclusion: remove magento/framework 101.0.0
    - Conclusion: don't install magento/framework 101.0.0
    - magepsycho/magento2-easy-template-path-hints dev-master requires magento/framework 100.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 100.0.19, 100.1.10].
    - Can only install one of: magento/framework[101.0.0, 100.0.2].
    - Can only install one of: magento/framework[101.0.0, 100.0.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.6].
    - Can only install one of: magento/framework[101.0.0, 100.0.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.8].
    - Can only install one of: magento/framework[101.0.0, 100.0.9].
    - Can only install one of: magento/framework[101.0.0, 100.1.0].
    - Can only install one of: magento/framework[101.0.0, 100.0.10].
    - Can only install one of: magento/framework[101.0.0, 100.0.11].
    - Can only install one of: magento/framework[101.0.0, 100.1.1].
    - Can only install one of: magento/framework[101.0.0, 100.0.12].
    - Can only install one of: magento/framework[101.0.0, 100.1.2].
    - Can only install one of: magento/framework[101.0.0, 100.1.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.13].
    - Can only install one of: magento/framework[101.0.0, 100.1.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.14].
    - Can only install one of: magento/framework[101.0.0, 100.1.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.15].
    - Can only install one of: magento/framework[101.0.0, 100.1.6].
    - Can only install one of: magento/framework[101.0.0, 100.1.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.16].
    - Can only install one of: magento/framework[101.0.0, 100.0.17].
    - Can only install one of: magento/framework[101.0.0, 100.1.8].
    - Can only install one of: magento/framework[101.0.0, 100.1.9].
    - Can only install one of: magento/framework[101.0.0, 100.0.18].
    - Can only install one of: magento/framework[101.0.0, 100.0.19].
    - Can only install one of: magento/framework[101.0.0, 100.1.10].
    - Installation request for magento/framework (locked at 101.0.0) -> satisfiable by magento/framework[101.0.0].

**Comment by MagePsycho** [comment]
Please re-try. This issue has been fixed.
