### ISSUE TITLE
Wrong install directory when using Composer

### ISSUE THREAD

**Issue by themoonwatcher** [MagePsycho/magento2-easy-template-path-hints#8]
The module files are placed in `vendor/magepsycho/magento2-easy-template-path-hints/src` when using Composer to install thus breaking Magento 2.2.2 because it looks for `.../etc/module.xml` and not for `.../src/etc/module.xml`.
If the files from `src` are copied to the parent directory - it works nice as always ;)

**Comment by Genaker** [comment]
@themoonwatcher  have the same issue. 

{"0":"Cannot read contents from file 
/vendor\/magepsycho\/magento2-easy-template-path-hints\/etc\/module.xml): failed to open stream: No such file

**Comment by gosteev** [comment]
yea, should be fixed. anyway, for now solution is pretty easy

**Comment by MagePsycho** [comment]
@themoonwatcher @Genaker @gosteev this issue has been FIXED in the new release.
