### ISSUE TITLE
Magento CE 2.3.0: Path hints are not showing on both front-end and admin panel

### ISSUE THREAD

**Issue by Kenop** [MagePsycho/magento2-easy-template-path-hints#9]
I followed the [guide](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/debug-theme.html) on Magento dev site, flushed cache, but path hints are not showing up after page reload. Googling the problem didn't help to find a solution. I'm using fresh install of Magento CE 2.3.0.

**Comment by MagePsycho** [comment]
@Kenop haven't tested in 2.3.0. Will updated once it's updated.

**Comment by MagePsycho** [comment]
The issue has been fixed @Kenop
